### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by walianitin** [walianitin/wallet#1]
Integrate  the front-end with backend

**Comment by HarshTripathi1103** [comment]
Hey @walianitin if no one is interested can u please assign me this issue and do i have to raise a PR ?

**Comment by walianitin** [comment]
Sure sure you can work ,and you have to raise a pr

**Comment by HarshTripathi1103** [comment]
U need Singup and Singin page connected to ur backend right ?

**Comment by walianitin** [comment]
yeah you got that right

**Comment by HarshTripathi1103** [comment]
i have raised a pr after solving the issue please review and merge it

**Comment by HarshTripathi1103** [comment]
did u reviewed the changes @walianitin ?

**Comment by walianitin** [comment]
i ll check it by today

**Comment by HarshTripathi1103** [comment]
ok

**Comment by walianitin** [comment]
yeh the code looks working .ill merge it

**Comment by HarshTripathi1103** [comment]
okay 🤝

**Comment by HarshTripathi1103** [comment]
did u reviewed the PR ?

**Comment by walianitin** [comment]
Yes

**Comment by HarshTripathi1103** [comment]
Then please 🙏 merge the PR
